version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - card-collection-network

networks:
  card-collection-network:
    driver: bridge

volumes:
  redis-data:
