import type { Metadata } from "next";
import "../../styles/authenticated/layout.scss";
import Navigation from "../../components/organisms/Navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <main className="layout">
      <Navigation position="top" />
      <section className="content-area">{children}</section>
      <Navigation position="bottom" />
    </main>
  );
}
