import type { Metadata } from "next";
import "../../styles/authenticated/layout.scss";
import TopNavigation from "../../components/organisms/TopNavigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <main>
      <TopNavigation />
      <section>
        {children}
      </section>
    </main>
  );
}
