import type { Metadata } from "next";
import "@/app/styles/authenticated/layout.scss";
import TopNavigation from "../../components/organisms/TopNavigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <main className="authenticated-layout">
      <TopNavigation />
      <section className="right-section">
        {children}
      </section>
    </main>
  );
}
